# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: avocure_development
  pool: 5
  username: akash
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: avocure_test
  pool: 5
  username: akash
  password: password1